MUSCLE (3.8) multiple sequence alignment


MGG_04118T0      -----AMTFETVAADGTIKSERIFKDINERTTSYT-------------------------
MGG_07293T0      FFPGQGVQKVGMLTPWLENFPSTARPIIQEIDDCL----------GYKLSDII-------
MGG_10011T0      CFGGQVSTSVGLDRDVFDRTA-ILRTHLDEVDAVA-RAQGAGSIYP--------------
MGG_16787T0      ------------------------------------------------------------
MGG_14042T0      ------------------------------------------------------------
MGG_09645T0      VFTGQGAQWAQMGAELVDKEP-VTNRK---------GELS--------------------
MGG_14831T0      AFTGQGAQWHAMGRGLS-VYK-TWRDSMAVSQQVL-TSLG----CPWSLGEELS------
MGG_13591T0      VFTGQGAQWPRMGAGLA-RFD-VYRESLEAANAYL-KTIG----CEWSVVDELS------
MGG_00806T0      VFTGQGAQWPTMGRGLM-AYP-TFRESLHEAEEYMTQTLR----CPWSLTYELC------
MGG_00233T0      IFTGQGAQWARMGIELL-RYE-VFAQSLRRADEYFRESLG----CAWSVLQELS------
MGG_08285        VFTGQGAQWAGMGIQLL-SRP-VFAASVAASTAYL-ARLG----CEWEPVRELE------
MGG_12214T0      VFTGQGAQYVGMGRGLL-RYP-AFKQALQQIDHVY-QRLG----CKWSLFDELN------
MGG_12613T0      VFCGQGAQWHAVGRELL-DYA-AFKSNIEAADSYIRQELG----ADFSLLEVLT------
MGG_13767T0      IFTGQGAQWFAMGRELL-AYD-VFRASVAEADAFIAGTLG----GGFSVLEELAR-----
MGG_08236T0      VFTGQGAQYARMAMGLLDRYQ-TFRSSINECDAFLSNELR----CPWSVIEELG------
MGG_04118T0      VFTGQGSQEQGMGMELYESSP-VAKEVWDRADKYL-MD----------------------
MGG_14945T0      VFTGQGAQWHAMGRELLASYP-VFQASLESFDACL-SRLG----ATFSLVAELTQ-----
MGG_04775T0      VFTGQGAQWHGMGRELYDSYP-VYAAAMDRADAKL-KELG----ATWSLLEELS------
MGG_05589T0      VFNGQGAQWWAMGRELYEQYP-VFAASIDLADGSL-ADLG----ATWSLVDELA------
MGG_10912T0      VFTGQGAQWAGMGRELMDEFP-SFRRTVQMLDSTL-QLLPHP--PTWTLRGALL------
MGG_03810T0      VFAGQGAQWPGMARQIIGDIP-FVQQRVVELEGHL-QDLASQDAPSWSLRDEL-------
MGG_11638T0      IFTGQGAQWAQMSKHLLINCP-IFKQTIHQLEDVL-RECPTP--PDWTISQELS------
MGG_09589        VFTGQGAQWPAMGRELILQEP-VFRRSIEACEAAL-SNLP--DAPDWSLKAELLK-----
MGG_14897        --------------DALATLP-VVADR-----------------PAWSLAEELS------
MGG_14943T0      IFTGQGAQYAGMMSGLLQASP-WALGRALELEKTLMDLLPAHDRPQNSLVGQLLSSASGK
MGG_15100T0      IFTGQGAQWPAMGKMLISTLP-HARDVISQLDQSL-SSLPPRYRPSWALHDQLM------
MGG_15272T0      VFTGQGAQWPAMMKQLVVRVP-SAARIVAELDVSL-QTLPKQYRPGWTLMEQLM------
MGG_14606T0      ------------------------------------------------------------
MGG_15097T0      VFTGQGAQWPRMGAELIEDSP-TVAGIVRRLDQSL-QSLPVRDRPSWTLREHLL------
MGG_12447        VFTGQGAQWARMGVDVINASP-AARAIFEDLEQSL-KTLPEEDRPSWSMLEELL------
MGG_00428T0      TFTGQGSFERGLCADLYDSCE-FLRTDVQRCEHLV-RAMGLPSILAAFQRPGVN------
MGG_07219T0      MFTGQGSHYAGLGKELYANHA-VFRQAINEFDRIS-QIHGFPSFMPLVDG----------
MGG_00241T0      TFTGQGAAYRGMASQLFETSP-QFRSGIMAAQRLC-DLYGFPSVVEYIQGQEQHRGA---
MGG_00241T0      ------------------------------------------------------------
MGG_08281T0      VFSGQGSEYPDMGSELYQTSP-VFRDTVDRCVHLC-ANQGFPSFSDMMLSDGAG------
                                                                             

MGG_04118T0      -----YRSPTGLLSATQFTQPALTLMEKASFEDM-KAKGLVPRDST---FAGHSLGEYSA
MGG_07293T0      -----RDGPNKLLTATPHAQPAIMATSILILRVLERDFGFSPLEHKVNFVLGHSLGEFAA
MGG_10011T0      -----AIFQTTPLADPVQLQVALLALQYATARCW-MDCGVEP--AS---VVGHSFGEFAA
MGG_16787T0      ---------------------------------------------------------MAA
MGG_14042T0      -------------DIRGPSMTVDTALQLALLAVL-ADWNVTP--AA---VVGHSSGKIAA
MGG_09645T0      -----KPKSESRLSEAQFSQPVLAALQIALVDLL-RSWGVQP--SA---VVGHSSGETPA
MGG_14831T0      -----RGEKDSRLRLTEYSQPICTALQIALVDLL-RSWAVEP--VA---VVGHSSGEIAA
MGG_13591T0      -----KSAGDSNINKAEFSQTLCTVLQVALVDLF-NEWGLQF--RA---VVGHSSGETAA
MGG_00806T0      -----KEAGASRINDAEFSQPVCTALQVALVDLL-RTWKVRP--HA---VVGHSSGEIAA
MGG_00233T0      -----ADKDRSNLKRAEYSQPLCTALQVALVDLL-DSWGIQP--AA---VAGHSSGEMAA
MGG_08285        -----KRGDESRLGRAEVSQAICTVLQIALVDEL-RSWGVRP--AR---VIGHSSGEIAA
MGG_12214T0      --------NGTTIDSPTRSQPLSTALQIALVHLL-RAFGIVP--KA---VVGHSSGEIAA
MGG_12613T0      -----ADQDSSRIDLAHVSQISTTAVQVALVDVL-FASNVVP--IA---VVGHSSGEIAA
MGG_13767T0      -----RDADATKIDQPLYSQTLCTVLQVALVDLL-ASWNLLP--RR---VVGHSSGEIGA
MGG_08236T0      -----RDVKTSKVDQPLYSQPLCTAIQVALVDLF-NSWGLTP--SS---VIGHSSGEIAA
MGG_04118T0      ------------------------TYGFAITNIV-K------------------------
MGG_14945T0      -----KDAKTSRISDAELSQPGCTGVQLALVDLL-RDWGVCP--DA---VVGHSSGEIGA
MGG_04775T0      -----KDGKTSKVSEAHISQPACTAVQLAITDLL-KSWGVVP--VA---VAGHSSGEICA
MGG_05589T0      -----KDEETTRVGEAHISQPACTAIQLALVDLL-RGWGVHP--TA---VAGHSSGEIAA
MGG_10912T0      -----EPPESSSINLASRSQPVCTAVQLALVRLL-RDWGVAP--GF---AVGHSSGEIAA
MGG_03810T0      -----GKVQGSNLDLAQFSQPLCTALQIIQIDLL-AAAGIRF--SA---VVGHSSGEIAA
MGG_11638T0      -----ADAENSRINIAAISQPLCTAVQIALVNVL-RAIGINF--HT---VVGHSSGEVAA
MGG_09589        -----TDQEDSRMSEAVLAQPATTAVEIGLVDVL-ASKGIRF--AA---VVGHSSGEMAA
MGG_14897        -----RGEKQSRIAEAEFAQPCTTAVEIALVDVL-AAHGVRF--SA---VVGHSSGEMAA
MGG_14943T0      DSSSAAAAAAANVMRAELSQPLCTMIQILLVDIL-NKAGVTL--DA---VVGHSSGEIAA
MGG_15100T0      -----LEGGSSNVHDARFSQPLCCAIQILLVQML-AAAGIKL--EV---VVGHSSGEIAC
MGG_15272T0      -----REGDESNVRLAAYSQPLCAAVQIVLVRLL-AAAGVAF--DA---IVGHSSGEIGC
MGG_14606T0      ------------------------------------------------------------
MGG_15097T0      -----APKESSQVYIASLSQPLCTALQIILVDLL-KVAGITF--SG---VVGHSSGEIGA
MGG_12447        -----APPETSRVYQANISQTVCTAVQVMMVQLL-RAAGIEF--SC---VVGHSSGEMAA
MGG_00428T0      -----SLDVSSRLLSPVALQLSHVCYQMALCNLW-RHLGLAP--KA---VVGHSLGEYAA
MGG_07219T0      -----SEPDVAKL-EPLIVQLGLCCFEMALAKLW-ASWGVKP--AA---VMGHSLGEYAA
MGG_00241T0      -----AAAAAAPEVVAAQEQLSLVALQTALVDLL-RFWGLRP--DV--------------
MGG_00241T0      -----------------MAAPLDEEPSTAVRRILRAPEGTGP--DV---VMGHSLGEYAG
MGG_08281T0      -----AKHDSSGVDRTVKKHLALVTLELALAAFW-RHAGVEP--SV---VVGHSLGEYAA
                                                                             

MGG_04118T0      LAALADVMPIESLVSVVFYRGL------------------------TMQVAVERDASGRS
MGG_07293T0      LVA-GGYLTFADSLRLVQRRAQAMAAATRAAREGRPDVE-----YGMVAIVTEPEYLPRL
MGG_10011T0      ACV-AGVLSLRDTVRLVACRARLVRDRWGADR------------GRMLAVEADLADVRDA
MGG_16787T0      AYA-AGFLTALNAVRMAYYRGNFCKLGRSPNVDCA---------SGTATLKKARGHFGSQ
MGG_14042T0      AVA-AGYMSSADAIRTAYLRGYGSKQILEPSQQEQAAPSS----LGMLAVGVGPDVAQSY
MGG_09645T0      AYA-AGALTAEDAFLLAYHRGAFKPLLRAAHS------------GGMAAVGLGRTDIE--
MGG_14831T0      AYT-AGFLSHESAVKVAWLRGQVSGTVSRD--------------GGMLAVNAPAEAMQAR
MGG_13591T0      AYA-AGAISKESAWRIAFWRGKLSAKLSDALEQPK---------GTMAAVGLTVDKAKEY
MGG_00806T0      AYA-AGQLSRQSSWRIAYYRGKLATKLIRSLRRRENSQDAHVKKTGMVAVGLDKEQTLAA
MGG_00233T0      AYA-IGALSAEDAWAAAYWRGNLDGRTSQPR-------------GAMLAAAMSEQAAQAL
MGG_08285        AYC-LGALSHSDAIAAAYFRGKASAAVAEASSKQATE-------MGMMAVGCSREQAQEL
MGG_12214T0      AYA-AGALSLESASKVSFVRGQLAGHLKQQLEVAQTP-------GAMMSVNLPEAEVPSY
MGG_12613T0      AYA-AGAVTRESAWKIAYYRGYCVASWQEKDHGPP---------GRMLAVGLSARDVQAF
MGG_13767T0      AYA-AGALDRQSAWKVAYCRGVVSAKPAAGDKR-----------GAMMAIGCTAEEVAPI
MGG_08236T0      AYS-AGAITRHSAWRIAYQRGVVSEKLVADSI--ASP-------TTMMSVGLSQEEVASY
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      AYA-AGALTLHECAAIAYFRGQSVLQLKAAYP--GLK-------GGMLAVGAGSEEVSEM
MGG_04775T0      AYA-AGIINFDSAVAIAYHRGRLIPVLKSRHP--DLA-------GGMMAVGGSESDMQPM
MGG_05589T0      AYS-AGIITFKSAMSIAYHRGRLIPMLKEQFP--ALQ-------GRMMAVGGSKSDVQGM
MGG_10912T0      AYA-AGRLTARQAIAVAYYRGYAVERSTTV--------------GAMMAAGLSQDEADGD
MGG_03810T0      AYA-AGLLSARDAMVVAYYRGLHSPRLAGKSKNSKG--------GSMMAAGISYAEALAV
MGG_11638T0      AYA-AGRITAPNAILIAYYRGLYAHVAGAPGSGVK---------GGMLAAGLSKLEA-ER
MGG_09589        LYA-AGFLSLQDAVRIAYYRGLHASRLAN------DN-------GAMLAVGLSWDAA-AR
MGG_14897        CYA-AGILTLRDAVRIAYYRGRHARLARSSGA--------------MLAVGLGWDAAEEQ
MGG_14943T0      AYA-AGRLSAATALAVAYYRGINT-KLAGGLD--GKK-------GAMSAAPLSYADA-CL
MGG_15100T0      AYA-AGLVTASQAIRIAYLRGFVSDKASSPNGVE----------GAMLAAGCSYKDAQE-
MGG_15272T0      AFA-AGYVSAAQAIRIAYLRGFTSVHAGQD--------------GAMLAAGMSLDDAKDL
MGG_14606T0      ---------------------------------------------AMLA-----------
MGG_15097T0      AYA-AGYLTASDAIRVAYYRGLHL-KLVT------TK-------GAMLAAGTTFADA-QE
MGG_12447        AYT-AGYLSARDAVRAAYFRGVHS-QLAKGSN--GQP-------GGMIAVGTNFEDA-EE
MGG_00428T0      LYA-AGVLTQADTISLVAGRARLMEELLESSTVP----------HAMVAVMAPEASVTAA
MGG_07219T0      LHV-AGVLSASDTIYLVGARAKLLVEKCTAGT------------HAMLAVMGSVSTVQEA
MGG_00241T0      --------------------------------------------GGM-------------
MGG_00241T0      LCA-AGVLSLGDTLYLVGRRAGLLGQHCRAGD------------YGMLVLPVGSGEADKM
MGG_08281T0      LHV-AGVLSLADVLHLVGNRARRLAAVCEPGA------------CGMLAVSASADAVGAF
                                                                             

MGG_04118T0      NYSM----------------------------CAVNPSRISKTFNEEALRFVVGNIAEGT
MGG_07293T0      VQAIREFLGHSSEGAKAESSASAAPIEHVSIANVNSKNQIVLSGELGRIKTLVAHVRQFL
MGG_10011T0      VAGS-----------------GGQ----AAVACYNGPRSFTLSGTTAAVEAVARDLDL-K
MGG_16787T0      LTML--------------------------------PRSVILNGGLVKVRKMQNLLSEKK
MGG_14042T0      LDKVNG----------P-SPDINN----VYIAGYSSLSSLAVPGPVSALTVLGAKLKD-D
MGG_09645T0      ----------------RGGFLRPG----VMVACDNSPSSVTLSGEADVLPAVMADIAA-R
MGG_14831T0      LGKL----------------TTGR----AVVACMNSPRACTVSGDRAAVDELHDLLKADE
MGG_13591T0      IDKVYE----------SGFQGVEK----LAVGCMNSPNSQTISGDVAQVEALVELLNS-E
MGG_00806T0      ISRV------------DSLVGEGS----LEIACMNSQESHTVSGDMAKLDALVEVLKS-E
MGG_00233T0      IAQV--------------PRSKGI----VVVGCVNSPSSVTLSGDEAAVVAASQLITE-Q
MGG_08285        IAGQ--------------NGCVD-----VTVACVNSPESITLSGHATELEKMAEVLQE-H
MGG_12214T0      LADK------------D-LLQDSN----ITIACINSPGNVTLAGDEAAIDAVKSCLDK-D
MGG_12613T0      IHQT----------------SKGS----VQVACHNGPSSVTLSGDEAAILEVQNILAE-A
MGG_13767T0      IAEV------------EEKLGAGE----LVIACYNSPHSLTISGDEAKVDALVEIASSRK
MGG_08236T0      LAGT-------------------D----VTVACINSPINVTVSGPVKSIEELYTRLDA-A
MGG_04118T0      ----------------------------------NNPKELTI------------------
MGG_14945T0      IKTM------------TPDP-ARR----VVVACVNSPGSITASGDVAAVEELQAKVEE-K
MGG_04775T0      IDAV------------K-RK-QQE----VRIACFNSPSSLTISGDASVLNDLERVIEE-E
MGG_05589T0      IDGL------------C-EK-Q------VRIACFNSPSSLTISGDEPALAELEKVVED-R
MGG_10912T0      IAAL---------------GLAGK----IRVACVNSPESVTISGDTDGIDEYKAVLDG-R
MGG_03810T0      VGLE---------------QFQGR----IAVAAHNSPASVTLSGDEDAILEAKELLTS-D
MGG_11638T0      LCAL--------------DNWRGR----LSAAASNSHTSVTLSGDLDAVKEMAQYLTE-Q
MGG_09589        FCDG------------D-RF-RGR----LWRAAKNSPSSVTLSGDAGAVAEAEAVLKA-Q
MGG_14897        ITAV--------------QRWRGR----LWLAARNSPSSVTISGDADAVEEAHAELQQ-R
MGG_14943T0      LCSQ------------P-RF-QGR----LSVAASNSPGSTTLSGDQDAVAEAEEELKS-Q
MGG_15100T0      LCGL--------------DMFRNR----ICVAASNAPDSVTISGDADAIEEAREVLED-E
MGG_15272T0      VELE---------------DFAGK----VCIAACNSPDSVTLSGDLDALEAVVEILQD-E
MGG_14606T0      -------------------------------VACNSPESATLSGDKNVLEEILEILQD-E
MGG_15097T0      LCSL------------P-AF-EGR----ACVAASNSPASVTLSGDADAIEEIQIILGE-E
MGG_12447        LCEL------------D-DF-KGR----LCVAASNSAELVTLSGDLDAVQEVKKILDA-E
MGG_00428T0      LGGS------------NLAATHG-----VSVCCRNSANNVVLGGPTASVVKVKALLEF-Q
MGG_07219T0      LGER-----------------ADS----TNVACINGPRETVLSGEASEMAEIAQQLGA-A
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      IANS-----------------RG-----CCIACKNTPSATVVSGPLKEIHDLQAAVRRDR
MGG_08281T0      LHRR-----------------RGGLLSSCSIACINAPNAVVVSGSAADLLAAQEALGQ-K
                                                                             

MGG_04118T0      ---G--------------WLLEIVNYN-IANMQYVCAGDLRAL-----------------
MGG_07293T0      ---G-------HDPRAVRLNSD-SPFH-SPIMRPAVAVVRDMLAAGGEGGGM--------
MGG_10011T0      ---GRAASGASKSVKVKLLNVS-HAFH-SPLVEPHLVEGLGRCAQTLTFSKQ--------
MGG_16787T0      ---N---------VSVRMLRVV-KAYH-SPRISV--------------------------
MGG_14042T0      ---G---------HFARLLQVD-LAYH-SPYMAS-VAFYYKKTLEQFCHFGPQGSRN---
MGG_09645T0      ATPG---------VLCRRLDVE-SAYHYADHMWT-VMPEFAAGVGGVDGIRS--------
MGG_14831T0      -------------VVCTKLPMD-VAYH-SFHMEA-AREQYEQALAGIPHLRP--------
MGG_13591T0      ---G---------VFARKLKVE-MAYH-SHLMNP-IAEEYAQSMGEIEPPGS--------
MGG_00806T0      ---N---------VFARKLSVG-IGYH-SRHMLP-IADEYVRLIGDIGSDLP--------
MGG_00233T0      ---G---------VFNRRLHVD-AAYH-SPHQSR-LSDEYLMRILHIAPKPI--------
MGG_08285        ---S---------IFHRRLKVE-IAYH-SPLMAA-VSDKYLSYI---SH-----IEPREA
MGG_12214T0      ---G---------IFAQKLHTG-VAYH-SAHMDQ-IACQYLIQMGELEGPAS--------
MGG_12613T0      ---G---------VFSRLVPVN-AAYH-SRHMEH-VAADYLQKLGSIEIRNV--------
MGG_13767T0      -------------LFARKLRVP-KAYH-SSHMLP-VSDEYRSLMGTLTGTPS--------
MGG_08236T0      ---E---------IFAKRLPVK-IGYH-SSVMRR-GSQEYEASLR--GKIEA--PSPSRQ
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      ---Q---------LFNRRVRVE-TAYH-SHHMEL-VADWYGAAVG--PL-DP---KATDL
MGG_04775T0      ---Q-------PEMFRRKLQVD-VAYH-SHHMNL-VADEYRDSIE--HLSKP---RNTD-
MGG_05589T0      ---Q---------MFHRRLVVD-VAYH-SHHMDL-VAEEYQAALA--HLPDP--SRSTG-
MGG_10912T0      ---G---------VFARLLKTDGRAYH-SHHMAA-IGGLYEDLVVE-ALASPAVQNDLDD
MGG_03810T0      ---G---------KFARLLRVD-QAYH-SHHMRP-CLAPYVASLQR-AGVGAVRPRP---
MGG_11638T0      ---G---------KFARKLIVD-TAYH-SAHMLA-PAEKYGESLSTFEIEAS--------
MGG_09589        ---N---------TTARRLKTD-KAYH-SPHMQA-CADAYLDSLRA-CGIKP--RVP---
MGG_14897        ---G---------VFSRLLRTG-KAYH-SPHMEP-PAGPYLQSMRA-CGIKP--TKP---
MGG_14943T0      ---S---------IKAKRLFVD-KAYH-SHHMRS-CAGAYAANLQRLSGFNK--P-----
MGG_15100T0      ---G---------KFARKVKVD-KAYH-SFHMEQ-CAEPYVRALLDSGCDAE--------
MGG_15272T0      ---G---------KFARLLRVD-KAYH-SHHMLP-CSEPYIAALEECGCATP--------
MGG_14606T0      ---Q---------KFARLLLVD-RAYH-SHHMFP-CSDPYITALNQ-CGCGV--PDG---
MGG_15097T0      ---K---------KFNRMLQVD-RAYH-SHHMNV-LAAPYKRSLEE-CGIKP--LRP---
MGG_12447        ---E---------KFNKQLQVD-KGYH-SHHMLP-CSEPYVASLQK-CGIQA--QVP---
MGG_00428T0      ---G---------HRCRLLDVD-MAFH-TAQVDP-ILDAFLKVSSRTRLCDP--------
MGG_07219T0      ---G---------FKCTQLKVP-FAFH-SAQVDP-ILDDFEKLARSVRFNTP--------
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      ---G---------IETTILPVQ-YGFH-SSQMEN-IAEDLERLAEEVHFSSP--------
MGG_08281T0      ---G---------IRSQRLAVD-FGYH-SAQMDA-VTSDLERLTAAVSFSAP--------
                                                                             

MGG_04118T0      ---------------------------------------------DTLTNVLNYLKAQK-
MGG_07293T0      --VTFPAKIPCVSNIS----------ARPFESE----AQLKDLLARQCLETVRWWDSIRY
MGG_10011T0      -------------TIHV---------EKAVEFEAGDERLDATYFPSQMRNPVYFHHAVKR
MGG_16787T0      -----------------------------------------------------FGDALR-
MGG_14042T0      ---GQGNSAVWFSSVNYVT-------GKRIDSE---LPVDAEYWKSNMVMPVQFNQALSS
MGG_09645T0      --AYRPLQVPMYSSVT----------AGRI------DQVSTAYYIRNMVSPVLFDGAVRA
MGG_14831T0      -----KSGPTMFSSVT----------GELVGAD----AMSPSYWVDNLVSPVNFTAASRS
MGG_13591T0      -ASKQGSPVEFFSSAY----------GCHVEHE---KLRQAAYWTTNLTSAVRFNESVAA
MGG_00806T0      -PSQGQSLPRYFSSLE----------GSEITLD---RLQSPDYWANNLTSPVRFHEAVEL
MGG_00233T0      -----KAGRGMFSTVT----------GRAVLNE---RALGPTNWVRNLISPVLFAQAVEA
MGG_08285        SDAMSEPAPIMVSSVT----------ASEATPD----MLGPYYWLANMMSPVLFSDGIVE
MGG_12214T0      --LEGAKRIPMVSSVT----------GKTIDTS---ELARPQYWVDNMVSPVQFFDAIRT
MGG_12613T0      -----TLGPVLYSSLT----------GSELSPS----RLGAKHWVKTLTCPVLFHQAVQT
MGG_13767T0      ------PDVQVASSVT----------GGLIPAG---DMTSADYWVQNLVSPVRFSQALVA
MGG_08236T0      SGSGGPVRTVMYSSVT----------GKAIGLG---DLNQPEYWVDNLVSAVKFAPALTA
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      KPKGGRHVVEFYSSLK----------GKRVRDL---AVLDTSYWVQNLTQPVLFSQALTA
MGG_04775T0      --------VQFHSSLF----------GKRVEGY---K-CTASYWVENLTCPVRFSEALSG
MGG_05589T0      --------VKFYSSLY----------GRLAEGS---E-LRASYWVENLTCPVRFSEAVEN
MGG_10912T0      AGQQNSSPAQWISSVT----------GQVVGDD--MPTAEPSYWRANLESPVLFAQVVEK
MGG_03810T0      ---HSNQETIWYSSVHRDGA------GQRVMTA-----VDCEYWAANMAQTVLFAGAVES
MGG_11638T0      ----EGNSTKWISSVYG---------DDRILEL---GELKSTYWTDNMVKPVLFREAIES
MGG_09589        ---A-RRDCVWISSVDGHANRYWASRNGDDGTAELLTSLAGPYWNENLVKPVLFEDAIVA
MGG_14897        ---TGRSPCVWISSVTGT--------ADMFWDGDFGGLASGQYWVDNMVQPVLFADAVTA
MGG_14943T0      ----GKGSTRWFSSVL----------VRDTTDA----LLDMSYWVDNMVQPVLFSQALEA
MGG_15100T0      --ATTEPSTIWLSSVR----------PGHCMRA---QDVTADYWKDNLLSPVLFSQALEH
MGG_15272T0      --DGQGNGVKWYSSVH----------EGRTMAA---EHVTARYWSDNLVSPVLFRQALEQ
MGG_14606T0      ---QDKGLLKWYSSVR----------DGKLVGF---ADITPGYWRDNLVSPVLFSHASGQ
MGG_15097T0      -----AGGCRWVSSVF----------TCDVSDIPSDVSLGSSYWVANLVQPVRFTEALEM
MGG_12447        ---GDATACRWISSVY----------VDDMTNL--DCRVQDRYWIENLAKPVMFSQALSH
MGG_00428T0      -------KIPYISSTL----------AKVVRNA---SDFGSDYFSRHCRKPVDLLGAVIA
MGG_07219T0      -------KVPVISPLL----------GKLVDDE----PINPKYLRDHARDAVDFLGGLVS
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      -------QIPVASTLL----------GRIIKDG---GTLGPKYLSRQTREAVDFVATVEA
MGG_08281T0      -------KLAVASTML----------ASVVKAS-DKITINADYLALQTRRPVNFVGAVQA
                                                                             

MGG_04118T0      -----------------------IDIEAMKAAMTVEDVKQHLQE----------------
MGG_07293T0      LDQR---------------EKVRRWIGIGPGKVGRNLVGKEVGMRG------------KG
MGG_10011T0      LADRYQSTGA-------------IFLEAGSASTITNMASRVLVGQP----------DGHF
MGG_16787T0      ----------------------EVWHGISSRDRPRDQRAKRLGV----------------
MGG_14042T0      MILDGPEAAN---------EADLMLIEIGPSNALAGPVSQVDKAGN-QGLAT------KV
MGG_09645T0      LLRD------------FGTATPPIFVEVGPHSAFAGPIRQIFQSEP--ARGA------TA
MGG_14831T0      LLHHSPAKTR-----TDRSAFASVLVEIGPHSALRSYLLDVFKAED---------RLTDL
MGG_13591T0      MLEAKMDEES-------LCDLVTDLLEIGPHAALQGLLRNINDATR---PNT------GV
MGG_00806T0      MLRADLGCNSQGESSTVGKKTVTDLLEIGPHAALRGPIRSIVKQVHQTAEW-------KI
MGG_00233T0      MLVS-------------KEANVQLLLEVGPHGALAAPCQNIMSKAG-----------VTV
MGG_08285        LVRPCIDGNH---TREEEVNTIDMMIEIGPHSTLAGPVDQTLSRHG----------LRDM
MGG_12214T0      LTSA-LKDQA---------GIITDLIEVGPHPALRRPVLDTLKTAI-KKSQR------EI
MGG_12613T0      LMRN---------------ANPTVVVEVSPTGIWEGTIRRILSAMD---------YREPV
MGG_13767T0      LCTA-NVARKQLKVGGGAELPVSHLVEVGPHGALQAAARDAVLSDP---------NYRHL
MGG_08236T0      LTSE-AKAGNRF------------FIELGPQSGLRRPIKDTLARAA---KDL------KW
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      MCTP-AE-GK---------DNLDLLIEMGPHPALEGPAKQILKSID--ALSK------KP
MGG_04775T0      MLEA-K--PE---------DGVSTLIEIGPHSALQGPIKQILAAAG--RP--------KL
MGG_05589T0      MLEP-SETSK---------TGVTALVELGPHSALQGPIKQILKAVG--GAAT------AV
MGG_10912T0      LLSP---------------GTPVHLVEIGPHSALEMPIKQTRTKVG--------IDAAKT
MGG_03810T0      AVTADASAAA---------QPFTTAIGLGPHGALRGPLEDILGSLSRTQGGNSTAERTQI
MGG_11638T0      AVSG--------------NNLYDVAVEVGPHPALKGPATETIKAAT----------GSTI
MGG_09589        ALTN----GG----------PFDACIEVGPHPALKGPVGQSIQPHL--PRRK------AL
MGG_14897        ALTN----GG----------PFDAAIEVGPHPALKGPVGQTVQAHL----------KRTI
MGG_14943T0      ACKT----LG----------PLDAIVEIGPHPALRGPVTQTLSNLW---PDS------DI
MGG_15100T0      ATRE--------------HGPVDLAIEVGCHPALKGPCLKTMEACSEPGAP-------EL
MGG_15272T0      AGLE---------------NTFDAAVEVGPHPTLKAPATNTLAAVG----------AEDL
MGG_14606T0      DTLE----NG-----------LDVAVEVGPHPSLEAPASTIISA-C---TAE------EV
MGG_15097T0      LYLG-ASMNG----------GFDLGIEVGPHPALQGPVKQTVQEFT---TDS------PL
MGG_12447        ALGG----DD----------KFDSVIEVGPHPALKGPASQTIQA-C---LGE------RL
MGG_00428T0      AKAEGLVGER------------SIAVEIGPAPVVCRMVKEVIGA--------------QM
MGG_07219T0      AQSAGAIDEK------------TVWLEVGPHPVCANMVKAAFGV--------------ST
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      ISAGGLADKD------------TIWVEIGPDAVNTSMVRKTLGIKD------------SN
MGG_08281T0      ANASLGGTDK------------AIWLEMGPRAVCASLVRSILPVSG----------RAST
                                                                             

MGG_04118T0      ------------------------------------------------------------
MGG_07293T0      IVKGAGVWG---------------------------------------------------
MGG_10011T0      KFQPIA------------------------------------------------------
MGG_16787T0      ------------------------------------------------------------
MGG_14042T0      KYCSALKRG---------------------------------------------------
MGG_09645T0      RYIPTLIRH---------------------------------------------------
MGG_14831T0      SYVGVLRRK---------------------------------------------------
MGG_13591T0      KYHHALKRG---------------------------------------------------
MGG_00806T0      GYATVLKRG---------------------------------------------------
MGG_00233T0      PYLSVLSRD---------------------------------------------------
MGG_08285        EYHSVLLRG---------------------------------------------------
MGG_12214T0      RYACILHRY---------------------------------------------------
MGG_12613T0      PYFSVLQNG---------------------------------------------------
MGG_13767T0      RYVSVLTRA---------------------------------------------------
MGG_08236T0      RYSPVLSST---------------------------------------------------
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      TYLASLVRN---------------------------------------------------
MGG_04775T0      PYASALVRN---------------------------------------------------
MGG_05589T0      TYDSALVRK---------------------------------------------------
MGG_10912T0      PYNSALLRG---------------------------------------------------
MGG_03810T0      PYTDVLTRN---------------------------------------------------
MGG_11638T0      PYFGVLDRK---------------------------------------------------
MGG_09589        PYCGALNRG---------------------------------------------------
MGG_14897        PYCGAMNRGADCVTSLSEALGFLWRGFGGGALRHPQDPGEPRPRMVKDLPPYAWDHTTSL
MGG_14943T0      SYVSLIQRG---------------------------------------------------
MGG_15100T0      PYVGCMRRG---------------------------------------------------
MGG_15272T0      PYTGCLQRG---------------------------------------------------
MGG_14606T0      PYTGCLQRG---------------------------------------------------
MGG_15097T0      AYTGLMKRG---------------------------------------------------
MGG_12447        PYFGCLSRG---------------------------------------------------
MGG_00428T0      QTFTSLHRH---------------------------------------------------
MGG_07219T0      VAVPTLRRNEA-------------------------------------------------
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      RLVPALKKG---------------------------------------------------
MGG_08281T0      LVLSTLNHH---------------------------------------------------
                                                                             

MGG_04118T0      ------------------------------------------------------------
MGG_07293T0      ------------------------------------------------------------
MGG_10011T0      ------------------------------------------------------------
MGG_16787T0      ------------------------------------------------------------
MGG_14042T0      ------------------------------------------------------------
MGG_09645T0      ------------------------------------------------------------
MGG_14831T0      ------------------------------------------------------------
MGG_13591T0      ------------------------------------------------------------
MGG_00806T0      ------------------------------------------------------------
MGG_00233T0      ------------------------------------------------------------
MGG_08285        ------------------------------------------------------------
MGG_12214T0      ------------------------------------------------------------
MGG_12613T0      ------------------------------------------------------------
MGG_13767T0      ------------------------------------------------------------
MGG_08236T0      ------------------------------------------------------------
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      ------------------------------------------------------------
MGG_04775T0      ------------------------------------------------------------
MGG_05589T0      ------------------------------------------------------------
MGG_10912T0      ------------------------------------------------------------
MGG_03810T0      ------------------------------------------------------------
MGG_11638T0      ------------------------------------------------------------
MGG_09589        ------------------------------------------------------------
MGG_14897        WRESRVSRNHRLRPQDRAFLLGRRCPDDTDAEPRWRNMLSLAELPWLRGHAFEGEALYPA
MGG_14943T0      ------------------------------------------------------------
MGG_15100T0      ------------------------------------------------------------
MGG_15272T0      ------------------------------------------------------------
MGG_14606T0      ------------------------------------------------------------
MGG_15097T0      ------------------------------------------------------------
MGG_12447        ------------------------------------------------------------
MGG_00428T0      ------------------------------------------------------------
MGG_07219T0      ------------------------------------------------------------
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      ------------------------------------------------------------
MGG_08281T0      ------------------------------------------------------------
                                                                             

MGG_04118T0      ------------------------------------------------------------
MGG_07293T0      ------------------------------------------------------------
MGG_10011T0      ------------------------------------------------------------
MGG_16787T0      ------------------------------------------------------------
MGG_14042T0      ------------------------------------------------------------
MGG_09645T0      ------------------------------------------------------------
MGG_14831T0      ------------------------------------------------------------
MGG_13591T0      ------------------------------------------------------------
MGG_00806T0      ------------------------------------------------------------
MGG_00233T0      ------------------------------------------------------------
MGG_08285        ------------------------------------------------------------
MGG_12214T0      ------------------------------------------------------------
MGG_12613T0      ------------------------------------------------------------
MGG_13767T0      ------------------------------------------------------------
MGG_08236T0      ------------------------------------------------------------
MGG_04118T0      ------------------------------------------------------------
MGG_14945T0      ------------------------------------------------------------
MGG_04775T0      ------------------------------------------------------------
MGG_05589T0      ------------------------------------------------------------
MGG_10912T0      ------------------------------------------------------------
MGG_03810T0      ------------------------------------------------------------
MGG_11638T0      ------------------------------------------------------------
MGG_09589        ------------------------------------------------------------
MGG_14897        AAYLVMLLEVAQFLAAGREVAFVQLSDVSFNRTLAIPEGGRAVEIITSAKVEERKGLRDG
MGG_14943T0      ------------------------------------------------------------
MGG_15100T0      ------------------------------------------------------------
MGG_15272T0      ------------------------------------------------------------
MGG_14606T0      ------------------------------------------------------------
MGG_15097T0      ------------------------------------------------------------
MGG_12447        ------------------------------------------------------------
MGG_00428T0      ------------------------------------------------------------
MGG_07219T0      ------------------------------------------------------------
MGG_00241T0      ------------------------------------------------------------
MGG_00241T0      ------------------------------------------------------------
MGG_08281T0      ------------------------------------------------------------
                                                                             

MGG_04118T0      -----------
MGG_07293T0      -----------
MGG_10011T0      -----------
MGG_16787T0      -----------
MGG_14042T0      -----------
MGG_09645T0      -----------
MGG_14831T0      -----------
MGG_13591T0      -----------
MGG_00806T0      -----------
MGG_00233T0      -----------
MGG_08285        -----------
MGG_12214T0      -----------
MGG_12613T0      -----------
MGG_13767T0      -----------
MGG_08236T0      -----------
MGG_04118T0      -----------
MGG_14945T0      -----------
MGG_04775T0      -----------
MGG_05589T0      -----------
MGG_10912T0      -----------
MGG_03810T0      -----------
MGG_11638T0      -----------
MGG_09589        -----------
MGG_14897        IRASVGFSVCR
MGG_14943T0      -----------
MGG_15100T0      -----------
MGG_15272T0      -----------
MGG_14606T0      -----------
MGG_15097T0      -----------
MGG_12447        -----------
MGG_00428T0      -----------
MGG_07219T0      -----------
MGG_00241T0      -----------
MGG_00241T0      -----------
MGG_08281T0      -----------
                            
