site_name: CusProSe documentation
nav:
    - Home: index.md
    - Installation: installation.md
    - Iterhmmbuild:
      - Overall procedure: ihb_introduction.md
      - Usage: ihb_usage.md
    - Prosecda:
      - Introduction: psd_introduction.md
      - Description: psd_description.md
      - Usage: psd_usage.md

theme: readthedocs
markdown_extensions:
    - footnotes
    - attr_list
    - toc:
        permalink: "#"
use_directory_urls: false
extra_css: [css/extra.css]
  # - css/extra.css